version: "3"
name: lit-bot-stack
services:
  lit-bot:
    container_name: lit-bot-container
    build:
      context: .
      dockerfile: Dockerfile
    image: lit-bot-image
    env_file:
      - "app/.env"
    restart: always
    volumes:
      - db-data:/app/database
volumes:
  db-data:
    name: "lit-bot-data"
