version: "3"
name: lit-bot-stack
services:
  lit-bot:
    container_name: lit-bot-container
    build:
      context: .
      dockerfile: Dockerfile
    image: lit-bot-image
    env_file:
      - ".env"
    restart: always
